# -*- coding: utf-8 -*-
"""DoNOTDELETE--By670Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sex62pEWLxqh4_SuJoTuQuoPDdv1nRTc
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')

drive.mount("/content/drive/", force_remount=True)
!ls

pip install pymarc

import csv

csv_out = csv.writer(open('/content/drive/My Drive/Data Services/NACOtoMeridianMapping/NACORecordsby670URIReferenceRev20241209Hurry.csv', 'w'), delimiter = ',', quotechar = '"', quoting = csv.QUOTE_MINIMAL)

from pymarc import MARCReader, Field, Subfield

with open('/content/drive/My Drive/Data Services/NACOtoMeridianMapping/NACOforAPI.mrc', 'rb') as fh:
    reader = MARCReader(fh)
    for record in reader:
      csv_record = {}
      try:
        for Field in record.get_fields('100'):
          field100a = (record['100']['a'])
          csv_record[field100a] = field100a
          field100c = record['100'].get_subfields('c')
          if field100c:
            field100c = str(field100c)
          else:
            field100c = ''
            csv_record[field100c] = field100c
          field100q = record['100'].get_subfields('q')
          if field100q:
            field100q = str(field100q)
          else:
            field100q = ''
            csv_record[field100q] = field100q
          field100d = record['100'].get_subfields('d')
          if field100d:
            field100d = str(field100d)
          else:
            field100d = ''
            csv_record[field100d] = field100d
        field400as = []
        field400cs = []
        field400qs = []
        field400ds = []

        for field in record.get_fields('400'):
          if record['400']:
            field400a = field.get_subfields('a')
            field400c = field.get_subfields('c')
            field400q = field.get_subfields('q')
            field400d = field.get_subfields('d')

            if field400a:
              field400as.extend([str(sf) for sf in field400a])
            else:
              field400as.append('No 400a')

            if field400c:
              field400cs.extend([str(sf) for sf in field400c])
            else:
              field400cs.append('No 400c')

            if field400q:
              field400qs.extend([str(sf) for sf in field400q])
            else:
              field400qs.append('No 400q')

            if field400d:
              field400ds.extend([str(sf) for sf in field400d])
            else:
              field400ds.append('No 400d')
          else:
            field400as.append('No 400')
            field400cs.append('No 400')
            field400qs.append('No 400')
            field400ds.append('No 400')
        field500a = ''
        field500c = ''
        field500q = ''
        field500d = ''
        for Field in record.get_fields('500'):
          if record['500']:
            field500a = record['500'].get_subfields('a')
            if field500a:
              field500a = str(field500a)
            else:
              field500a = ''
            field500c = record['500'].get_subfields('c')
            if field500c:
              field500c = str(field500c)
            else:
              field500c = ''
            field500q = record['500'].get_subfields('q')
            if field500q:
              field500q = str(field500q)
            else:
              field500q = ''
            field500d = record['500'].get_subfields('d')
            if field500d:
              field500d = str(field400d)
            else:
              field500d = ''
          csv_record[field500a] = field500a
          csv_record[field500c] = field500c
          csv_record[field500q] = field500q
          csv_record[field500d] = field500d
        field510a = ''
        field510b = ''
        field510w = ''
        field510i = ''
        for Field in record.get_fields('510'):
          if record['510']:
            field510a = record['510'].get_subfields('a')
            if field510a:
              field510a = str(field510a)
            else:
              field510a = ''
            field510b = record['510'].get_subfields('b')
            if field510b:
              field510b = str(field510b)
            else:
              field510b = ''
            field510w = record['510'].get_subfields('w')
            if field510w:
              field510w = str(field510w)
            else:
              field510w = ''
            field510i = record['510'].get_subfields('i')
            if field510i:
              field510i = str(field510i)
            else:
              field510i = ''
          csv_record[field510a] = field510a
          csv_record[field510b] = field510b
          csv_record[field510w] = field510w
          csv_record[field510i] = field510i
        field046f = ''
        field046g = ''
        field0462 = ''
        for Field in record.get_fields('046'):
          if record['046']:
            field046f = record['046'].get_subfields('f')
            if field046f:
              field046f = str(field046f)
            else:
              field046f = ''
            field046g = record['046'].get_subfields('g')
            if field046g:
              field046g = str(field046g)
            else:
              field046g = ''
            field0462 = record['046'].get_subfields('2')
            if field0462:
              field0462 = str(field0462)
            else:
              field0462 = ''
            csv_record[field046f] = field046f
            csv_record[field046g] = field046g
            csv_record[field0462] = field0462
        field368c = ''
        field368d = ''
        field3682 = ''
        for Field in record.get_fields('368'):
          if record['368']:
            field368c = record['368'].get_subfields('c')
            if field368c:
              field368c = str(field368c)
            else:
              field368c = ''
            field368d = record['368'].get_subfields('d')
            if field368d:
              field368d = str(field368d)
            else:
              field368d = ''
            field3682 = record['368'].get_subfields('2')
            if field3682:
              field3682 = str(field3682)
            else:
              field3682 = ''
          csv_record[field368c] = field368c
          csv_record[field368d] = field368d
          csv_record[field3682] = field3682
        field378q = ''
        for Field in record.get_fields('378'):
          if record['378']:
            field378q = record['378'].get_subfields('q')
            if field378q:
              field378q = str(field378q)
            else:
              field378q = ''
            csv_record[field378q] = field378q
        field373a = ''
        field3732 = ''
        for Field in record.get_fields('373'):
          if record['373']:
            field373a = record['373'].get_subfields('a')
            if field373a:
              field373a = str(field373a)
            else:
              field373a = ''
            field3732 = record['373'].get_subfields('2')
            if field3732:
              field3732 = str(field3732)
            else:
              field3732 = ''
          csv_record[field373a] = field373a
          csv_record[field3732] = field3732
        field374a = ''
        field3742 = ''
        for Field in record.get_fields('374'):
          if record['374']:
            field374a = record['374'].get_subfields('a')
            if field374a:
              field374a = str(field374a)
            else:
              field374a = ''
            field3742 = record['374'].get_subfields('2')
            if field3742:
              field3742 = str(field3742)
            else:
              field3742 = ''
            csv_record[field374a] = field374a
            csv_record[field3742] = field3742
        field370a = ''
        field370b = ''
        field370c = ''
        field370e = ''
        field3702 = ''
        for Field in record.get_fields('370'):
          if record['370']:
            field370a = record['370'].get_subfields('a')
            if field370a:
              field370a = str(field370a)
            else:
              field370a = ''
            field370b = record['370'].get_subfields('b')
            if field370b:
              field370b = str(field370b)
            else:
              field370b = ''
            field370c = record['370'].get_subfields('c')
            if field370c:
              field370c = str(field370c)
            else:
              field370c = ''
            field370e = record['370'].get_subfields('e')
            if field370e:
              field370e = str(field370e)
            else:
              field370e = ''
            field3702 = record['370'].get_subfields('2')
            if field3702:
              field3702 = str(field3702)
            else:
              field3702 = ''
        Field024s = record.get_fields('024')
        field024alist = []
        field0242list = []
        if not Field024s:
          field024alist.append(str("No 024"))
          field0242list.append(str("No 024"))
        else:
          for Field024 in Field024s:
            field024as = Field024.get_subfields('a')
            if not field024as:
              field024alist.append(str("No 024 subfield a"))
            else:
              for i in field024as:
                field024alist.append(str(i))
            field0242s = Field024.get_subfields('2')
            if not field0242s:
              field0242list.append(str("No 024 subfield 2"))
            else:
              for i in field0242s:
                field0242list.append(str(i))
        Field670s = record.get_fields('670')
        if not Field670s:
          field670a = str("No 670")
          field670b = str("No 670")
          field670u = str("No 670")
          field670w = str("No 670")
        else:
          for Field670 in Field670s:
            field670as = Field670.get_subfields('a')
            if not field670as:
              field670a = str("No subfield a")
            else:
              field670a = str(field670as)
            field670bs = Field670.get_subfields('b')
            if not field670bs:
              field670b = str("No subfield b")
            else:
              field670b = str(field670bs)
            field670us = Field670.get_subfields('u')
            if not field670us:
              field670u = str("No subfield u")
            else:
              field670u = str(field670us)
            field670ws = Field670.get_subfields('w')
            if not field670ws:
              field670w = str("No subfield w")
            else:
              field670w = str(field670ws)
            for field024a in field024alist:
              for field0242 in field0242list:
                csv_out.writerow([field100a, field100c, field100q, field100d, field046f, field046g, field0462, field368c, field368d, field3682, field370a, field370b, field370c, field370e, field3702, field378q, field373a, field3732, field374a, field3742, field024a, field0242, field670a, field670b, field670u, field670w, field400as, field400cs, field400qs, field400ds, field500a, field500c, field500q, field500d, field510a, field510b, field510w, field510i])
      except KeyError:
            print([field100a])
            pass